### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by jheavejimenez** [Eloquade/Recursion#1]
![Anurag's GitHub stats](https://github-readme-stats.vercel.app/api?username=Eloquade&count_private=true&show_icons=true)

[![Top Langs](https://github-readme-stats.vercel.app/api/top-langs/?username=Eloquade&layout=compact&langs_count=10)](https://github.com/anuraghazra/github-readme-stats)

**Comment by Eloquade** [comment]
!
